process_manager_admin_executables:
  type: coreshop.resources
  resource: |
    alias: process_manager.executable
    additional_routes:
      getConfig:
        path: get-config
        action: getConfig
        methods: [GET]
      run:
        path: run
        action: run
        methods: [GET,POST]
      list-by-type:
        path: list-by-type
        action: listByType
        methods: [GET]


process_manager_admin_processes:
  type: coreshop.resources
  resource: |
    alias: process_manager.process
    only: ['list', 'delete']
    additional_routes:
      getLogDownload:
        path: log-download
        action: logDownload
        methods: [GET]
      getLogReport:
        path: log-report
        action: logReport
        methods: [GET]
      stopProcess:
        path: stop-process
        action: stop
        methods: [GET]
      clear:
        path: clear
        action: clear
        methods: [POST]
